spring:
  application:
    name: auth-service

keycloak:
  username: user-manager
  password: 1111
  clientId: demo
  clientSecret: demo
  serverUrl: http://localhost:9080
  realm: dev
  scope: openid