version: "3.8"

services:
  guideme-keycloak:
    container_name: guideme-keycloak
    image: quay.io/keycloak/keycloak:23.0.4
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      KC_PROXY: edge
      KC_DB: dev-file
      KC_HTTP_PORT: 9080
      KC_HTTPS_PORT: 8443
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:8443:8443
    command: [ 'start-dev', '--import-realm' ]
    networks:
      - guideme-keycloak-network
  guideme-db:
      image: mysql:8.0
      container_name: guideme-db
      environment:
        MYSQL_ROOT_PASSWORD: raaxiim
        MYSQL_DATABASE: hotels
        MYSQL_USER: raaxiim
        MYSQL_PASSWORD: raaxiim
      networks:
        - guideme-db-network
      ports:
        - "3307:3306"
      volumes:
        - guide:/var/lib/mysql

  guide-me-auth:
    networks:
      - guideme-keycloak-network
    container_name: guide-me-auth
    ports:
      - "8080:8080"
    depends_on:
      - guideme-keycloak
    build:
      context: ./auth-service/
    environment:
      KEYCLOAK_URL: http://guideme-keycloak:9080
  guide-me-user:
    container_name: guide-me-user
    build:
      context: ./user-service
    ports:
      - "8083:8083"
    networks:
      - guideme-user-network
  guide-me-file:
    container_name: guide-me-file
    ports:
      - "8082:8082"
    networks:
      - guideme-file-network
    build:
      context: ./file-service
  hotel:
    build:
      context: ./hotel-booking
    ports:
      - "8081:8081"
    networks:
      - guideme-keycloak-network
      - guideme-db-network
      - guideme-user-network
      - guideme-file-network
    environment:
      IMAGE_REPR_URL: http://localhost:8082
      KEYCLOAK_URL: http://guideme-keycloak:9080/realms/dev
      GUIDEME_DB: jdbc:mysql://guideme-db:3306/hotels
      GUIDEME_DB_USER: raaxiim
      GUIDEME_DB_PASSWORD: raaxiim
      GUIDEME_FILE: http://guide-me-file:8082/api/file
      GUIDEME_USER: http://guide-me-user:8083/api/users
    depends_on:
      - guideme-db
      - guide-me-file
      - guide-me-user
      - guideme-keycloak
volumes:
  guide:
networks:
  guideme-keycloak-network:
    driver: bridge
  guideme-db-network:
    driver: bridge
  guideme-user-network:
    driver: bridge
  guideme-file-network:
    driver: bridge



