version: '3.8'

services:
  guideme-keycloak:
    container_name: guideme-keycloak
    image: quay.io/keycloak/keycloak:23.0.4
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      KC_PROXY: edge
      KC_DB: dev-file
      KC_HTTP_PORT: 9080
      KC_HTTPS_PORT: 8443
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:8443:8443
    command: [ 'start-dev', '--import-realm' ]
  guideme-db:
    image: mysql:8.0
    container_name: guideme-db
    environment:
      MYSQL_ROOT_PASSWORD: raaxiim
      MYSQL_DATABASE: hotels
      MYSQL_USER: raaxiim
      MYSQL_PASSWORD: raaxiim
    ports:
      - "3307:3306"
    volumes:
      - guide:/var/lib/mysql
volumes:
  guide:
