spring:
  application:
    name: bazaar
  datasource:
    url: jdbc:mysql://localhost:3307/hotels
    password: raaxiim
    username: raaxiim
  liquibase:
    enabled: true
    password: raaxiim
    user: raaxiim
    url: jdbc:mysql://localhost:3307/hotels
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/dev
file-service:
  serverUrl: http://localhost:8082/api/file
file:
  serverUrl: http://localhost:8082/api/file
user-service:
  serverUrl: http://localhost:8083/api/users
server:
  port: 8084
