spring:
  application:
    name: bazaar
  datasource:
    url: ${GUIDEME_DB}
    password: ${GUIDEME_DB_PASSWORD}
    username: ${GUIDEME_DB_USER}
  liquibase:
    enabled: true
    password: ${GUIDEME_DB_PASSWORD}
    user: ${GUIDEME_DB_USER}
    url: ${GUIDEME_DB}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}
file-service:
  serverUrl: ${GUIDEME_FILE}
file:
  serverUrl: ${IMAGE_REPR_URL}
user-service:
  serverUrl: ${GUIDEME_USER}
server:
  port: 8084
